### PR TITLE
rq draft

### PR DESCRIPTION
**Pull request by beaman33**
Jerry says I need to know how to do PR

Major updates from this branch:

- Two new ansatz: Winger and difference coordinates
- bug fix in MC samples
- Remove JLD dependency and add JSON3 for io

### CODE REVIEW

**Comment by cortner** [comment]
Good. :) Can you add some details what this PR is about?

**Comment by CheukHinHoJerry** [comment]
Bernie says that he wants to try writing the test for rq and its grad by himself so I asked him to create a PR and I can easily look at this.

**Comment by cortner** [comment]
Excellent - now we have something to test. Hopefully it's the code that's buggy and not the test :)

**Comment by CheukHinHoJerry** [comment]
@beaman33 please confirm it works as expected - and after that I think we can merge to the 1D experimental branch for now.

**Comment by CheukHinHoJerry** [comment]
After we merge this PR to `1dlux`, I will clean up everything and try to merge `main` to `1dlux` and integrate back later, including cleaning up package dependence. Currently any 1d related stuffs is extremely messy.

**Comment by CheukHinHoJerry** [comment]
CI failing due to method overwrite - will fix that in the new clean up in `1dlux`.

**Pull request merged**
