### PR TITLE
Gradient w.r.t. parameters

### PR DESCRIPTION
**Pull request by cortner**
CC @CheukHinHoJerry

### CODE REVIEW

**Comment by cortner** [comment]
this is ready to merge as well, we can do both together tomorrow.

**Comment by cortner** [comment]
I've partially fixed the performance now. There is probably more to be found, but I'm happy for now. This is ready to merge for me. @CheukHinHoJerry please confirm.

Test 1: with a minimal model 
```julia
Nel = 4
polys = legendre_basis(8)
wf = BFwf(Nel, polys; ν=3)
```
we get 
```
[ Info: ψ
  4.780 μs (6 allocations: 672 bytes)
[ Info: ∇ψ
  12.250 μs (30 allocations: 71.36 KiB)
[ Info: Δψ
  38.750 μs (153 allocations: 95.41 KiB)
[ Info: ∇Δψ
  57.667 μs (183 allocations: 297.28 KiB)
```

Test 2: with a larger model 
```julia 
Nel = 8
polys = legendre_basis(10)
wf = BFwf(Nel, polys; ν=4)
```
we get
```
[ Info: ψ
  78.875 μs (6 allocations: 1.52 KiB)
[ Info: ∇ψ
  159.083 μs (30 allocations: 797.11 KiB)
[ Info: Δψ
  633.291 μs (183 allocations: 889.19 KiB)
[ Info: ∇Δψ
  726.209 μs (245 allocations: 3.19 MiB)
```

**Comment by CheukHinHoJerry** [comment]
Sure! Maybe we can merge later today if you are free. I will be at IAM in the afternoon.

**Comment by cortner** [comment]
Since there are no conflicts, I think I can just merge then. (I'm at home again today)

**Pull request merged**
