### PR TITLE
BFwf with many grads and laps + Hyperduals

### PR DESCRIPTION
**Pull request by CheukHinHoJerry**
This branch is a super-branch of 3d-2 and 3d. Sorry for messing it up.

This branch is ready for review and it implements a basic BFwf_chain with:

- grad w.r.t X and parameter (with Zygote pb and Hyperdual)
- laplacian w.r.t. X (with Hyperdual)
- gradp laplacian (with Hyperdual + Zygote on gradp)

This should be enough to proceed after some performance fix. @cortner Please review this when you are free.

CC @DexuanZhou

### CODE REVIEW

**Comment by CheukHinHoJerry** [comment]
@cortner I think I am done from my end, the profview now looks like this, which the bottle neck is at `P4ML/sparsesymmprod.jl` which I am not sure how to resolve:


image


Another thing that ignores me is that the CI keeps failing since `ACEcore.jl`, which we used in `bf1d`, is not found in the registry. Did we remove that or did I do somthing wrong?

**Comment by cortner** [comment]
I have an idea - I'll draft something, we can talk on Zulip.

**Comment by cortner** [comment]
See  ACEsuit/Polynomials4ML.jl#45

**Comment by CheukHinHoJerry** [comment]
I removed the CI of J1.0 due to Julia version constrain by P4ML@v0.2.2. I also removed the `ACEcore` dependency, replace all of them by new P4ML and make sure all the tests are added back to `run_test.jl` (so that CI is actually meaningful) and everything works fine for now (at least from what I can tell).

TODO:

1. Remove `DenseLayer` implementation and use the one in P4ML
2. benchmarks again after things being rewrote in P4ML and swapping out the DenseLayer
3. there are some import conflicts that I should look into.

**Comment by CheukHinHoJerry** [comment]
Close and reference to #22

**Pull request closed without merging**
